name: Build CustomSwatches Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout SML
        uses: actions/checkout@v4
        with:
          repository: satisfactorymodding/SatisfactoryModLoader
          path: SML
      
      - name: Checkout Mod
        uses: actions/checkout@v4
        with:
          path: SML/Mods/CustomSwatches
      
      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2
      
      - name: Setup gh CLI
        run: |
          winget install --id GitHub.cli -e --source winget
        shell: powershell
      
      - name: Download CSS Engine
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          mkdir C:\ue
          cd C:\ue
          gh release download --repo satisfactorymodding/UnrealEngine -p "UnrealEngine-CSS-Editor-Win64.7z.*"
          7z x "UnrealEngine-CSS-Editor-Win64.7z.001" -o"C:\ue" -aoa
          Remove-Item "UnrealEngine-CSS-Editor-Win64.7z.*"
        shell: powershell
      
      - name: Download Wwise
        env:
          GH_TOKEN: ${{ secrets.BOT_TOKEN }}
          WWISE_EMAIL: ${{ secrets.WWISE_EMAIL }}
          WWISE_PASSWORD: ${{ secrets.WWISE_PASSWORD }}
        run: |
          gh release download --repo mircearoata/wwise-cli -p "wwise-cli_windows_amd64.exe" -O wwise-cli.exe
          .\wwise-cli.exe download --sdk-version "2023.1.14.8770" --filter Packages=SDK --filter DeploymentPlatforms=Windows_vc160 --filter DeploymentPlatforms=Windows_vc170
          .\wwise-cli.exe integrate-ue --integration-version "2023.1.14.3555" --project "$env:GITHUB_WORKSPACE\SML\FactoryGame.uproject"
        shell: powershell
      
      - name: Generate project files
        run: |
          cd SML
          C:\ue\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.exe -projectfiles -project="$env:GITHUB_WORKSPACE\SML\FactoryGame.uproject" -game -engine
        shell: powershell
      
      - name: Build FactoryEditor
        run: |
          cd SML
          C:\ue\Engine\Build\BatchFiles\Build.bat FactoryEditor Win64 Development -project="$env:GITHUB_WORKSPACE\SML\FactoryGame.uproject" -NoHotReload
        shell: powershell
      
      - name: Package Mod
        run: |
          C:\ue\Engine\Build\BatchFiles\RunUAT.bat -ScriptsForProject="$env:GITHUB_WORKSPACE\SML\FactoryGame.uproject" PackagePlugin -Project="$env:GITHUB_WORKSPACE\SML\FactoryGame.uproject" -dlcname=CustomSwatches -build -server -clientconfig=Shipping -serverconfig=Shipping -platform=Win64 -serverplatform=Win64 -nocompileeditor -installed
        shell: powershell
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CustomSwatches
          path: SML/Saved/ArchivedPlugins/CustomSwatches/*.zip
